export let products = [
    {
        id: 1,
        title: "Ketchup parrillero",
        price: 1000,
        stock: 5,
        description: "Salsas de San Antonio de Areco",
        category: "Salsas",
        img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697471917/ketchupparrillero_6_faverj.jpg",
    },
    {
        id: 2,
        title: "Salsa picante",
        price: 700,
        stock: 2,
        description: "Salsas de San Antonio de Areco",
        category: "Salsas",
        img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697483494/ajipicante_2_okokpn.jpg",
    },
    {
        id: 3,
        title: "Chimi agridulce",
        price: 800,
        stock: 6,
        description: "Salsas de San Antonio de Areco",
        category: "Salsas",
        img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697483494/chimiagridulce_1_1_i43uuk.jpg",
    },
    {
        id: 4,
        title: "Chimi picantón",
        price: 900,
        stock: 9,
        description: "Salsas de San Antonio de Areco",
        category: "Salsas",
        img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697483495/picanto%CC%81ntronco_1_atba3y.jpg",
    },
];
