export let products = [
  {
    id: 1,
    title: "Ketchup parrillero",
    price: 1000,
    stock: 5,
    description: "Con ajo, ají molido y orégano",
    category: "salsas",
    img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697471917/ketchupparrillero_6_faverj.jpg",
  },
  {
    id: 2,
    title: "Salsa picante",
    price: 700,
    stock: 2,
    description: "Con ají picante, locoto y tomates",
    category: "salsas",
    img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697483494/ajipicante_2_okokpn.jpg",
  },
  {
    id: 3,
    title: "Chimi agridulce",
    price: 800,
    stock: 6,
    description: "Con vino del contratista",
    category: "chimis",
    img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697483494/chimiagridulce_1_1_i43uuk.jpg",
  },
  {
    id: 4,
    title: "Chimi picantón",
    price: 900,
    stock: 9,
    description: "Con locoto",
    category: "chimis",
    img: "https://res.cloudinary.com/dnixufsko/image/upload/v1697483495/picanto%CC%81ntronco_1_atba3y.jpg",
  },
];
